# Basics

- [DataTypes and Attributes](#datatypes-and-attributes)
- [Anatomy of an Array](#anatomy-of-array)
- [Attributes](#attributes)
- [Integration with other DS Packages](#integration-with-other-ds-packages)


In [1]:
# Importing numpy
import numpy as np

## DataTypes and Attributes

NumPy pretty much has one DataType, the N-D array (n-dimensional array). NumPy arrays are a fundamental data structure in the world of scientific computing with Python. They are essentially multidimensional arrays that offer several advantages over standard python lists.

NumPy arrays are designed for storing large amounts of data compactly in memory. This is because all the elements in a NumPy array must be of the same data type, which allows for optimizations in storage and computations. Operations in NumPy arrays are much faster than on Python lists because NumPy can leverage vectorized operations, which perform calculations on entire arrays at once instead of iterating through each element individually.

NumPy offers a rich set of functions for working with array. These functions include mathematical operations, linear algebra operations, random number generation, and file input/output.

NumPy arrays come with several key attributes that provide information about their structure and data.


In [2]:
# Creating arrays
a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])

a3 = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
        ],
        [
            [10, 11, 12],
            [13, 14, 15],
            [16, 17, 18],
        ],
    ],
)

In [3]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [4]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Anatomy of array

![anatomy of array](../images/array_anatomy.jpg)

The image above covers the basic anatomy of an array. It's composed of 3 basic details, a name of the actual structure, the dimension, and the shape.

If the array is one dimensional, it is a vector, if it's multidimensional it's called a matrix.

The dimension shows how many axes or direction an array has. Axis 0 refers to the layers of an array, axis 0 refers to the rows of an array, and finally, axis 2 refers to the columns of an array.

Shape specifies the size of the array along each dimension, more specifically it shows in order of axes (0, 1, 2) how many layers, rows and columns the array is composed of respectively.

## Attributes

### `ndim`

This attribute represents the number of axes or dimensions the array has. A 1D array is a single row, a 2D array is a table-like structure, and so on.

### `shape`

This attribute represents the number of axes (or dimensions) the array has. A 1D array is a single row, a 2D array is a table-like structure, and so on.

### `size`

This attribute represents the total number of elements in the array. It's essentially the product of all the numbers in the shared tuple. You can access the data type using the dtype attribute.

### `dtype`

This attribute specifies the data type of the elements in the array. All elements in a NumPy array must have the same data type, which could be integers, floats, strings, or other supported types.


In [5]:
# Number of dimensions of array
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [6]:
# Array's shape
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [7]:
# Array's size
a1.size, a2.size, a3.size

(3, 6, 18)

In [8]:
# Type of array data
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

## Integration with other DS packages


In [9]:
# Create DataFrame from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5