# Creating arrays

Numpy provides a versatile approach to array creation. It goes beyond simple data structures, offering functions to craft arrays pre-filled with zeros, ones or random values. Specialised functions handle specific spacings or identity matrices. This flexibility ensures arrays perfectly align with a variety of data analysis tasks.

- [Functions to create arrays](#functions-to-create-arrays)
  - [.array](#array)
  - [.ones](#ones)
  - [.zeros](#zeros)
  - [.arrange](#arange)
  - [.eye](#eye)
- [Random arrays](#random-arrays)
  - [.random.randint](#randomrandint)
  - [.random.rand](#randomrand)
  - [.random.random](#randomrandom)
  - [.random.seed](#randomseed)


In [17]:
# Importing numpy
import numpy as np

## Functions to create arrays

### `.array`

Creates an array from a list, tuple, etc. This is the most basic way of creating an array.

### `.ones`

This creates an array of the specified size filled with ones.

### `.zeros`

Works much like the aforementioned `ones` function, but instead creates an array of the specified size filled with zeros.

### `.arange`

This function creates an array based on a range function. Receives arguments very much like the range function, with start, stop and step.

### `.eye`

Creates an Identity matrix based on the value received as argument. Since Identity matrices

### `.unique`

Although not a tool for creating arrays, this method allow fast insight into all of the unique numbers in the array.


In [18]:
# Creating sample array
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [19]:
# Checking array's type
sample_array.dtype

dtype('int64')

In [20]:
# Creates an array filled with ones
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
# Checking type of array
type(ones)

numpy.ndarray

In [22]:
# Creating array filled with zeros
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# Creating an array based on a range function (start, stop, step)
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [34]:
# Creates identity matrice of size 3
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
# Creates empty array
empty_array = np.empty((3, 3))
empty_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Random arrays

Numpy offers extensive functionality for crafting random arrays. This goes beyond simple uniform distributions, allowing you to generate arrays with elements drawn from various uniform distributions or by selecting from existing data. This flexibility empowers you to create random data suited to diverse simulation and analysis scenarios.

### `.random.randint`

This method generates one or more random integers. It takes three arguments, `low`, that defines the starting number (inclusive), `high`, that defines the limit for the number generation (exclusive), and `size`, that sets the size of the array.

### `.random.rand`

Generates an array of the specified size filled with random floating-point numbers, between 0 and 1. As an argument it takes a tuple of two values, the first represents the amount of rows, and the second the amount of columns of the matrix.

### `.random.random`

This method works exactly like the previous one, generating random floating-point numbers of value between 0 and 1. The main difference between the two methods is how the arguments are passed, where `.random.rand` takes a tuple with the size of the array as values in that tuple, this method takes the values separately as arguments.

### `.random.seed`

The `.random.seed` method in Numpy's random module is used to initialize the random number generator. It sets a starting point for the sequence of random numbers that will be generated. Since computers cannot generate true randomness, they rely on algorithms that produce a sequence of numbers appearing random, called pseudorandom numbers. With the same seed value, the `.random.seed` method ensures the random number generator generates the exact same sequence of random numbers every time the code is run. This allows for reproducibility in simulations or experiments that rely on randomness.

As you may imagine, using different seeds will lead to entirely different sequences of random numbers being generated. This is crucial for generating fresh randomness whenever needed.


In [24]:
# Creating random array (low, high, size)
random_array = np.random.randint(low=0, high=10, size=(3, 5))
random_array

array([[7, 6, 1, 8, 3],
       [2, 4, 6, 3, 4],
       [2, 1, 9, 6, 3]])

In [25]:
# Getting array's shape and size
random_array.size, random_array.shape

(15, (3, 5))

In [26]:
# Creating random array based only on tuple as argument
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.31118827, 0.75550127, 0.95617997],
       [0.20997533, 0.98372051, 0.49441991],
       [0.71393518, 0.68252607, 0.29842868],
       [0.05257151, 0.88541845, 0.02838727],
       [0.28212467, 0.66351709, 0.5306667 ]])

In [27]:
# Getting array's size and shape
random_array_2.size, random_array_2.shape

(15, (5, 3))

In [28]:
# Creating arary based on dimensions as argument
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.76448376, 0.59271598, 0.89892994],
       [0.38916576, 0.30612428, 0.25897026],
       [0.28063144, 0.0021157 , 0.1459736 ],
       [0.39009586, 0.48979814, 0.43820696],
       [0.46852356, 0.5197118 , 0.7564589 ]])

In [29]:
# Pseudo-random numbers
np.random.seed(seed=0)  # Setting a seed

random_array_4 = np.random.randint(
    10, size=(5, 3))  # Numbers don't change once a seed is set
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])