# NumPy practice


In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 3-dimensional NumPy array using np.array()
a3 = np.array(
    [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]
)

In [4]:
# Attributes of 1d array (shape, ndim, datatype, size, type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [5]:
# Attributes of 2d array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [6]:
# Attributes of 3d array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [46]:
# Import pandas and create a DataFrame out of one of the created arrays
import pandas as pd

pd.DataFrame(a2)

0  1  2
0  1  2  3
1  4  5  6

In [45]:
# Create array of shape (10, 2) with only ones
np.ones(shape=(10, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros(shape=(7, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [48]:
# Create an array within a range of 0 and 100 with step 3
np.arange(start=0, stop=100, step=3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array_1 = np.random.randint(low=0, high=10, size=(7, 2))
random_array_1

array([[7, 7],
       [0, 5],
       [9, 8],
       [2, 7],
       [7, 6],
       [8, 9],
       [3, 5]])

In [12]:
# Create a random array of floats between 0 and 1 of size
random_array_2 = np.random.random(size=(3, 5))
random_array_2

array([[0.99178918, 0.1029609 , 0.17807209, 0.41675083, 0.02596315],
       [0.59673992, 0.79040366, 0.64025254, 0.884544  , 0.24062951],
       [0.18098152, 0.99471729, 0.99671809, 0.2153858 , 0.2031715 ]])

In [13]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 and 10 size (4, 6)
random_array_3 = np.random.randint(low=0, high=10, size=(4, 6))
random_array_3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [22]:
# Create an array of random numbers between 1 and 10 of size (3, 7) and save it to a variable

random_array_4 = np.random.randint(low=1, high=10, size=(3, 7))

# Find the unique elements
np.unique(random_array_4)

array([1, 2, 3, 5, 6, 7, 8, 9])

In [15]:
# Find the 0'th index of the latest array you created
random_array_4[0]

array([9, 1, 3, 7, 4, 9, 3])

In [16]:
# Get the first two rows of the array you just created
random_array_4[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [44]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_4[:2, :2]

array([[9, 7],
       [7, 8]])

In [51]:
# Create a random array of numbers between 0 and 10 and an array of ones, both of size (3,5)
random_array_5 = np.random.randint(low=0, high=10, size=(3, 5))
ones = np.ones(shape=(3, 5))

In [52]:
# Add the two arrays together
random_array_5 + ones

array([[ 8.,  9.,  5.,  1.,  3.],
       [10.,  8.,  6.,  8.,  9.],
       [ 4.,  1.,  1., 10.,  4.]])

In [53]:
# Create another array of ones shaped (5, 3)
ones_2 = np.ones(shape=(5, 3))

In [55]:
# Try add the array of ones and the other most recent array together
random_array_5 + ones_2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [56]:
# Create another array of shape (3, 5)
ones_3 = np.ones(shape=(3, 5))

In [57]:
# Subtract the new array of ones from the other most recent array
random_array_5 - ones_3

array([[ 6.,  7.,  3., -1.,  1.],
       [ 8.,  6.,  4.,  6.,  7.],
       [ 2., -1., -1.,  8.,  2.]])

In [60]:
# Multiply the ones array with the latest array
random_array_5 * ones_3

array([[7., 8., 4., 0., 2.],
       [9., 7., 5., 7., 8.],
       [3., 0., 0., 9., 3.]])

In [62]:
# Take the latest array to the power of 2 using '**'
random_array_5**2

array([[49, 64, 16,  0,  4],
       [81, 49, 25, 49, 64],
       [ 9,  0,  0, 81,  9]])

In [63]:
# Do the same thing with np.square()
np.square(random_array_5)

array([[49, 64, 16,  0,  4],
       [81, 49, 25, 49, 64],
       [ 9,  0,  0, 81,  9]])

In [65]:
# Finding the mean of the latest array using np.mean()
np.mean(random_array_5)

4.8

In [66]:
# Finding the maximum of the latest array using np.max()
np.max(random_array_5)

9

In [67]:
# Finding the minimum of the latest array using np.min()
np.min(random_array_5)

0

In [68]:
# Find the standard deviation of the latest array
np.std(random_array_5)

3.2083225108042575

In [69]:
# Find the variance of the latest array
np.var(random_array_5)

10.293333333333335

In [70]:
# Reshape the latest array to (3, 5, 1)
random_array_5.reshape(3, 5, 1)

array([[[7],
        [8],
        [4],
        [0],
        [2]],

       [[9],
        [7],
        [5],
        [7],
        [8]],

       [[3],
        [0],
        [0],
        [9],
        [3]]])

In [71]:
# Transpose the latest array
random_array_5.T

array([[7, 9, 3],
       [8, 7, 0],
       [4, 5, 0],
       [0, 7, 9],
       [2, 8, 3]])

In [73]:
# Create two arrays of random integers between 0 and 10 one of size (3, 3) and other of size (3, 2)
random_array_6 = np.random.randint(low=0, high=10, size=(3, 3))

random_array_7 = np.random.randint(low=0, high=10, size=(3, 2))

In [74]:
# Perform a dot product on the two newest arrays just created
random_array_6.dot(random_array_7)

array([[19, 12],
       [20, 24],
       [ 7,  7]])

In [75]:
# Create two arrays of random integers between 0 and 10 both of size (4, 3)
random_array_8 = np.random.randint(low=0, high=10, size=(4, 3))

random_array_9 = np.random.randint(low=0, high=10, size=(4, 3))

In [76]:
# Perform a dot product on the two newest arrays just created
random_array_8.dot(random_array_9)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [77]:
# Take the latest two arrays, perform a transpose on one of them and a dot product on both
random_array_8.dot(random_array_9.T)

array([[11, 15, 21,  9],
       [79, 74, 97, 50],
       [72, 51, 54, 39],
       [64, 32, 25, 29]])

In [78]:
# Compare two arrays with '>'
random_array_9 > random_array_8

array([[ True,  True,  True],
       [False, False, False],
       [False,  True, False],
       [False,  True, False]])

In [79]:
# Compare two arrays with '>='
random_array_9 >= random_array_8

array([[ True,  True,  True],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False]])

In [81]:
# Find which elements of the first array are greater than 7
random_array_8 > 7

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [83]:
# Which parts of each array are equal?
random_array_8 == random_array_9

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False]])

In [84]:
# Sort one of the arrays you just created are in ascending order
random_array_9.sort()

In [86]:
# Sort the indexes of one of the arrays
random_array_9.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [87]:
# Find the index with the maximum value in one of the arrays
random_array_9.argmax()

8

In [88]:
# Find the index with the minimum value in one of the arrays
random_array_9.argmin()

6

In [89]:
# Find the indexes with the maximum values down the 1st axis
random_array_9.argmax(axis=1)

array([2, 1, 2, 1])

In [90]:
# Find the indexes with the minimum values across the 0th axis (axis = 0)
random_array_9.argmax(axis=0)

array([0, 1, 2])

In [91]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[ 0.00914435, -0.3655393 ,  0.64908673, -1.22287354,  0.53633603],
       [-0.91469093,  0.62054822, -0.16093738, -0.3882644 , -0.88551237],
       [-0.35674503,  0.5561218 ,  1.04386061,  0.52644816,  1.36388652]])

In [104]:
# Create an array with 1- evenly spaced numbers between 1 and 100
np.linspace(start=1, stop=100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])