# Sorting arrays

NumPy's array sorting capabilities are essential for data analysis. Sorting allows for efficient organization of massive datasets, making it a breeze to spot trends, perform calculations, and visualize data. Sorted arrays are the workhorses of many data processing tasks, enabling faster computations and improving the clarity of visualizations.

Here are some of the methods provided by NumPy for sorting arrays:

## `.sort()`

This method sorts the elements of an array in-place, modifying the original array. It sorts in ascending order by default. You can optionally specify the axis argument to sort along a particular axis of a multidimensional array.

## `.argsort()`

This method returns the indices that should sort the original array. It doesn't modify the original array. This is useful when you want to obtain the order for sorting but don't want to alter the original data. These indices can be used with other array manipulation operations.

## `.argmin()`

This method returns the index of the first occurrence of the minimum value in the array along a specific axis. It doesn't modify the original array.

## `.argmax()`

This method returns the index of the first occurrence of the maximum value in the array along a specific axis. Much like other functions, it doesn't modify the original array.


In [18]:
# Importing numpy and creating array
import numpy as np

a1 = np.array([1, 2, 3])

random_array = np.random.randint(10, size=(3, 5))

a1, random_array

(array([1, 2, 3]),
 array([[3, 4, 0, 0, 6],
        [4, 5, 0, 5, 6],
        [2, 4, 7, 8, 5]]))

In [14]:
# Sorting array by axis
np.sort(random_array)

array([[0, 6, 7, 8, 8],
       [2, 2, 5, 5, 9],
       [1, 1, 8, 8, 9]])

In [11]:
# Sorting the indexes of the arrays
np.argsort(a1), np.argsort(random_array)

(array([0, 1, 2]),
 array([[2, 4, 1, 0, 3],
        [2, 4, 0, 3, 1],
        [3, 4, 0, 1, 2]]))

In [22]:
# Finding the index of smallest element in array
np.argmin(a1), np.argmin(random_array, axis=0), np.argmin(random_array, axis=1)

(0, array([2, 0, 0, 0, 2]), array([2, 2, 0]))

In [23]:
# Finding the index of biggest element in array
np.argmax(a1), np.argmax(random_array, axis=0), np.argmax(random_array, axis=1)

(2, array([1, 1, 2, 2, 0]), array([4, 4, 3]))