# Viewing arrays

There are many ways of visualizing data contained in arrays. Although NumPy itself doesn't directly create visualizations, it offers some simple tools to visualize data from within the arrays themselves.

- [Index-based inspection](#index-based-inspection)
- [Slicing](#slicing)


In [1]:
import numpy as np

In [2]:
# Creating random array
random_array = np.random.randint(10, size=(5, 3))

random_array

array([[9, 4, 3],
       [4, 5, 8],
       [1, 0, 0],
       [5, 0, 5],
       [6, 2, 6]])

In [3]:
# Finding unique numbers there are in the array
np.unique(random_array)

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [4]:
# Creating arrays
a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])

a3 = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
        ],
        [
            [10, 11, 12],
            [13, 14, 15],
            [16, 17, 18],
        ],
    ],
)

a4 = np.random.randint(10, size=(2, 3, 4, 5))

## Index-based inspection

You can access individual elements within the array using their index. This can be done in simple vectors or in matrices. Elements are accessed through the dimensions defined in the arrays shape. For example `array[3]` would show the fourth element in the array, if this array is one-dimensional, if not, it only show the entire row that is contained. To show an element via index in a multi-dimensional array, use multiple indexes, one for each dimension of the array.

```python
# Shows the third element in the fourth row of array
array[3][2]

# or

array[3, 2]
```

## Slicing

NumPy also supports slicing, much like in python strings. This slicing can be done either sectionally, showing contents of an array in a range, `array[3:5]`, or conditionally, `array[array > 8]`. This slicing must also follow the principles of dimensional arrays, making it so that if an array has multiple dimensions, this slicing should be specific to each element


In [5]:
# You can find the elements of an array via index
a1[0], a2[0], a3[0]

(1,
 array([1. , 2. , 3.3]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [6]:
# Getting the third element of the first row of array
a2[0, 2], a2[0][2]

(3.3, 3.3)

In [7]:
# Slicing arrays is also possible
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [8]:
# Showing array
a4

array([[[[1, 4, 9, 0, 3],
         [1, 7, 9, 6, 3],
         [7, 0, 9, 9, 2],
         [6, 5, 7, 9, 2]],

        [[5, 7, 8, 4, 3],
         [3, 5, 7, 9, 0],
         [5, 0, 6, 2, 0],
         [7, 1, 1, 6, 1]],

        [[8, 0, 4, 6, 4],
         [6, 9, 3, 0, 0],
         [0, 2, 5, 3, 3],
         [8, 7, 4, 3, 0]]],


       [[[7, 5, 6, 0, 2],
         [4, 7, 0, 1, 8],
         [7, 2, 3, 4, 2],
         [9, 5, 3, 9, 0]],

        [[6, 5, 1, 8, 3],
         [6, 6, 3, 7, 2],
         [0, 9, 7, 8, 3],
         [8, 6, 9, 8, 1]],

        [[0, 3, 9, 6, 6],
         [5, 6, 4, 1, 0],
         [1, 9, 9, 7, 6],
         [6, 4, 8, 1, 7]]]])

In [9]:
a4[:, :, :, :4]

array([[[[1, 4, 9, 0],
         [1, 7, 9, 6],
         [7, 0, 9, 9],
         [6, 5, 7, 9]],

        [[5, 7, 8, 4],
         [3, 5, 7, 9],
         [5, 0, 6, 2],
         [7, 1, 1, 6]],

        [[8, 0, 4, 6],
         [6, 9, 3, 0],
         [0, 2, 5, 3],
         [8, 7, 4, 3]]],


       [[[7, 5, 6, 0],
         [4, 7, 0, 1],
         [7, 2, 3, 4],
         [9, 5, 3, 9]],

        [[6, 5, 1, 8],
         [6, 6, 3, 7],
         [0, 9, 7, 8],
         [8, 6, 9, 8]],

        [[0, 3, 9, 6],
         [5, 6, 4, 1],
         [1, 9, 9, 7],
         [6, 4, 8, 1]]]])